### PR TITLE
omnireader package syntax fix

### PR DESCRIPTION
**Pull request by jali7001**
I'm dumb sorry.

### CODE REVIEW

**Comment by lkilcommons** [comment]
Just so you know you can do it either way:
```{python}
from nasaomnireader import omnireader
```
or

```{python}
from nasaomnireader.omnireader import omni_interval
```

**Comment by jali7001** [comment]
Do you have a preference?

**Comment by lkilcommons** [comment]
Stylistically, I prefer 'from foo.bar import specific_thing', since it makes clear at the top of the file what functionality from a particular package you want to use. But it doesn't matter, functionally.

**Comment by jali7001** [comment]
Lol I'm sorry there's another thing I didnt see till now. Pwetty pwease PR.

Also, would you be interested in having test_ovation_utilities a lot more
fleshed out? Part of the reason I'm only finding these bugs now is because
I'm only finding them as I run amgeo. The other part is because I'm stupid.

**Comment by lkilcommons** [comment]
If you want to write more tests, go for it. Also, pretty much everything in geospacepy v0.2 takes julian date. I decided to standardize on that to sidestep some weirdness with arrays of datetimes.

The tests in OvationPyme (and nasaomnireader) are pretty sad. Better than nothing, but nowhere near complete.

Part of the reason for that is that it is hard to numerically test if output makes physical sense. The other part is that it's much easier to write the code with unit testing in mind than add unit tests at the end, and I wrote these before I understood that. To make them really testable some refactoring would probably be required.

**Comment by lkilcommons** [comment]
For test_ovation_utilities specifically, a good first step would be a test which checks the cache_omni_interval decorator applied to a dummy function. Maybe just something like:
```
@cached_omni_interval
def return_oi_tbounds(dt,oi):
    return oi['Epoch'][0],oi['Epoch'][1]

def test_cached_oi_matched_passed_time():
     dt = datetime.datetime(2010,5,29,1,0,0)
     odt_min,odt_max = return_oi_tbounds(dt)
     assert((dt >= odt_min) and (dt <= odt_max))
```

**Pull request merged**
