### PR TITLE
Python 3 compatibility updates and some PEP8 compliance

### PR DESCRIPTION
**Pull request by drsteve**
Python 2 is rolling up towards end-of-life, and OvationPyme isn't yet Python 3 compatible.
This PR adds Python 3 compatibility and makes a lot of formatting changes to move towards PEP8 compliance. I haven't added any code that would be incompatible with Python 2.7.

Summary of changes:
- PEP8: Tabs changed to 4 spaces across most of code base
- PEP8: spaces inserted behind commas, etc.
- PEP8: imports organized by standard library, then third-party
- PEP8: line continuations set to indent at start of broken phrase
- PEP8: Removed trailing whitespace
- Py3: print treated as function
- Py3: explicit integer divide on array indices (must be int)
- Py3: replaced many legacy C-style string format statements with string format method
- Py3: compatible iteration over dicts
- Py3: force range iterator to list
- Py3: set explicit relative imports
- Removed empty file (season_epoch.py)

Due to a bug in numpy, genfromtxt didn't work correctly under Python 3 until version 1.15. I didn't add the workaround, so use of Python 3 requires numpy >= 1.15

`functionaltests.py` runs (and doesn't look crazy), but requires changing the data path in geospacepy-lite's config script, where the default data directory is hardcoded to `/home/liamk/mirror/omni`. This is far from ideal, but should be addressed as a geospacepy-lite issue.

Running the test suite produces the same results as the current master branch. That is, this PR doesn't change the numerical results (as far as the testing shows). However, the current master branch at `lkilcommons` fails one of the tests. Specifically,
```
    def test_flux_same_as_idl(seasonal_flux_estimator, idl_call_results):
        """
        Check the seasonal flux is the same as produced
        by the IDL code for the same season and auroral type
        for a given i_mlt,j_mlat
        """
        j_mlat, i_mlt = idl_call_results['j_mlat'], idl_call_results['i_mlt']
        idl_dF = idl_call_results['dF']
        py_flux = seasonal_flux_estimator.estimate_auroral_flux(idl_dF, i_mlt, j_mlat)
        idl_flux = idl_call_results['je']
>       assert py_flux == idl_flux
E       assert 0.049330695727270855 == 0.0549602
```
I get the same numerical result (and hence the same failure) under both Python 2.7 and Python 3.5. The discrepancy is unchanged by this PR. Assuming that you can confirm (and it's not just me) I would suggest merging the PR and then addressing the test failure as a separate issue.

Happy to answer any questions about the PR, or make additional commits to fix any issues you spot.

### CODE REVIEW

**Comment by lkilcommons** [comment]
Thanks for doing this! I've just gone ahead and merged your PR here, but I will need to pull it down and check things are still behaving properly.
Also Just a heads up, someone raised an issue which led me to realize that I had been weighting the different seasons' coefficients incorrectly, which was also making the southern hemisphere results invalid (you can check out the closed issue for details). I don't know if you were making your changes before or after I committed the fix but might want to check. Also I added some new notebooks for inspecting the model output for different aurora types and seasons interactively as part of trying to debug that issue.

**Comment by drsteve** [comment]
Thanks!
I did notice the changes you made, including the coefficient weighting. I'd just finished the first round of changes so I had to rebase my branch against your commits and then cherry-pick/resolve all of mine so they still played over the top of yours... My bad really, I should've submitted the PR earlier!

**Comment by lkilcommons** [comment]
Hey, something went weird with the PR merge and I had to go back a re-add a bunch of my recent changes. I made a branch from my last commit before merging the PR and then merged that branch, manually resolving the conflicts. You'll be pleased to know that I've fixed my editor so it does 4 spaces like its supposed to, but I don't know that I got all of your spacing fixes. I think I got all of the string formatting fixes though.
If you have a chance I'd appreciate it if you could pull the latest branch and check that things still work with Python 3.

**Comment by drsteve** [comment]
Sorry about the delay getting back to you. I'm just starting to look at this, but I think what happened is that after you merged you continued working from an earlier commit that didn't have the changes...
I've attached a screenshot from qgit showing the git history.
image

Anyway, I'll take a look through and do some basic Python 3 testing, then get back to you.

**Comment by drsteve** [comment]
Well, everything still seems to work under Python 3. (3.6.7, running on WSL)

The test failure I mentioned in my initial post is still present, but the tests run, the `functionaltests.py` script runs and produces reasonable looking output. It looks like everything is more-or-less in line with the original PR, so I'm happy enough to call that a success.

Edit: built from the wrong branch before declaring success. It looks like a few bits of Python 3 syntax are still missing. I'll sync my master with upstream and then fix. I'll send a new PR when that's done.

**Pull request merged**
